/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Tue Sep 03 11:47:22 2024 */

/* parameterized module instance */
int_pll __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), 
    .LOCK( ));
